    # -*- mode: ruby -*-
    # vi: set ft=ruby :
     
    Vagrant.configure('2') do |config|
     
      # OS
      config.vm.box = 'hashicorp/bionic64'
     
      # IP
      config.vm.network 'private_network', ip: '10.0.0.100'
      config.vm.hostname = 'devops.vagrant.vm'
     
      # VirtualBox Config
      config.vm.provider :virtualbox do |vb|
     
        # Virtual Machine Name 
        vb.name = 'reverse-netcentric'
     
        # Memory
        vb.memory = 2048
       
        # procnum
        vb.cpus = 2
       
      end
      config.ssh.username = "vagrant"
      config.ssh.password = "vagrant"
      config.vm.synced_folder "login/", "/home/vagrant/share/"
      config.vm.provision "file", source: "./nginx_conf", destination: "/home/vagrant/nginx_conf"
      
      ####### Install Puppet Agent #######
      config.vm.provision "shell", path: "./bootstrap.sh"      
      
      config.vm.provision :shell do |shell|
        shell.inline = "puppet module install puppetlabs-apt;
                        puppet module install puppet-nginx;"          
      end     
      #config.vm.provision "shell", path: "sudo cp /home/vagrant/nginx_conf/cert* /etc/nginx/ && chown root /etc/nginx/cert*"     
      # Puppet provisioning
      config.vm.provision :puppet do |puppet|
     
        # Manifestos path 
        puppet.manifests_path = 'puppet/manifests'
     
        # Initial manifiesto's name
        puppet.manifest_file = 'reverse4.pp'

        # Puppet modules path
        #puppet.module_path = "puppet/modules"

        # Puppet options
        puppet.options = [
          '--verbose',
          '--debug',
        ]
     
      end
     
    end